@startuml
start
:Пользователь выбирает "Добавить книгу";
:Вводит название, автора, год;
if (Год корректен?) then (yes)
  :Создать объект Book;
  :Вызвать LibraryService.AddBook;
  :BookRepository сохраняет книгу в БД;
  :Подтверждение пользователю;
else (no)
  :Сообщение об ошибке;
endif
stop
@enduml
